pr: none
trigger: none
schedules:
- cron: "0 * * * *"
  displayName: Hourly
  branches:
    include:
    - main
  always: true

variables:
- group: 'Scheduled ML Pipeline Variables'

stages:
- stage: StartPipeline
  displayName: 'Start Pipeline'

  jobs:
  - job: StartPipeline
    displayName: 'Start Pipeline'
    pool:
      vmImage: 'windows-2019'

    steps:
    - task: AzureCLI@2
      displayName: 'az cli: submit pipeline run'
      inputs:
        azureSubscription: 'NK-AIRS'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az extension add -n azure-cli-ml
          az ml run submit-pipeline -i $(pipeline_id) -w $(workspace_name) -g $(resource_group_name)
  
